"""phase_4_task_system

Revision ID: d4f30616b6f8
Revises: f2602a69bdcc
Create Date: 2026-04-22 13:27:21.402099
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd4f30616b6f8'
down_revision: Union[str, None] = 'f2602a69bdcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('max_seats', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_families_created_by'), 'families', ['created_by'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('balance_idr', sa.DECIMAL(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('balance_pts', sa.DECIMAL(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=True)
    op.create_table('family_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', name='familymemberrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_family_members_family_active', 'family_members', ['family_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_family_members_family_id'), 'family_members', ['family_id'], unique=False)
    op.create_index('ix_family_members_user_active', 'family_members', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_family_members_user_id'), 'family_members', ['user_id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=False),
    sa.Column('invite_code', sa.String(length=6), nullable=False),
    sa.Column('invitee_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('SENT', 'ACCEPTED', 'EXPIRED', 'CANCELLED', name='invitationstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_family_id'), 'invitations', ['family_id'], unique=False)
    op.create_index('ix_invitations_family_status', 'invitations', ['family_id', 'status'], unique=False)
    op.create_index(op.f('ix_invitations_invite_code'), 'invitations', ['invite_code'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('source_wallet_id', sa.Uuid(), nullable=True),
    sa.Column('destination_wallet_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('IDR', 'PTS', name='currency'), nullable=False),
    sa.Column('type', sa.Enum('ALLOWANCE', 'TASK_REWARD', 'BONUS', 'EXPENSE', 'PTS_EXCHANGE', 'SUBSCRIPTION', name='transactiontype'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_wallet_id'], ['wallets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_wallet_id'], ['wallets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_dest_wallet_created', 'transactions', ['destination_wallet_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_transactions_destination_wallet_id'), 'transactions', ['destination_wallet_id'], unique=False)
    op.create_index('ix_transactions_family_created', 'transactions', ['family_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_transactions_family_id'), 'transactions', ['family_id'], unique=False)
    op.create_index(op.f('ix_transactions_source_wallet_id'), 'transactions', ['source_wallet_id'], unique=False)
    op.create_index('ix_transactions_src_wallet_created', 'transactions', ['source_wallet_id', 'created_at'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reward_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('reward_currency', sa.Enum('IDR', 'PTS', name='currency'), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'SUBMITTED', 'APPROVED', 'REJECTED', 'COMPLETED', name='taskstatus'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_type', sa.Enum('DAILY', 'WEEKLY', 'CUSTOM', name='recurrencetype'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reward_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reward_transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_assigned_status', 'tasks', ['assigned_to', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_assigned_to'), 'tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_tasks_family_id'), 'tasks', ['family_id'], unique=False)
    op.create_index('ix_tasks_family_status', 'tasks', ['family_id', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index('ix_tasks_family_status', table_name='tasks')
    op.drop_index(op.f('ix_tasks_family_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to'), table_name='tasks')
    op.drop_index('ix_tasks_assigned_status', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_transactions_src_wallet_created', table_name='transactions')
    op.drop_index(op.f('ix_transactions_source_wallet_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_family_id'), table_name='transactions')
    op.drop_index('ix_transactions_family_created', table_name='transactions')
    op.drop_index(op.f('ix_transactions_destination_wallet_id'), table_name='transactions')
    op.drop_index('ix_transactions_dest_wallet_created', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_invitations_invite_code'), table_name='invitations')
    op.drop_index('ix_invitations_family_status', table_name='invitations')
    op.drop_index(op.f('ix_invitations_family_id'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_family_members_user_id'), table_name='family_members')
    op.drop_index('ix_family_members_user_active', table_name='family_members')
    op.drop_index(op.f('ix_family_members_family_id'), table_name='family_members')
    op.drop_index('ix_family_members_family_active', table_name='family_members')
    op.drop_table('family_members')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_families_created_by'), table_name='families')
    op.drop_table('families')
    # ### end Alembic commands ###
