"""
Security utilities — password hashing, JWT tokens, refresh token handling.

Choices:
- Argon2id (via argon2-cffi): memory-hard, resistant to GPU attacks
- Pepper: global secret mixed in BEFORE hashing (on top of auto-generated salt)
- JWT: python-jose with HS256
- Refresh token: 32-byte cryptographically random hex string, SHA-256 hashed before DB storage
"""

import hashlib
import secrets
from datetime import UTC, datetime, timedelta

from argon2 import PasswordHasher
from argon2.exceptions import InvalidHashError, VerifyMismatchError
from jose import JWTError, jwt

from app.config import get_settings

# ------------------------------------------------------------------ #
# Argon2id hasher — use recommended defaults
# ------------------------------------------------------------------ #
_ph = PasswordHasher(
    time_cost=2,       # iterations
    memory_cost=65536, # 64MB — balance of security vs. speed for web API
    parallelism=2,
    hash_len=32,
    salt_len=16,
)


# ------------------------------------------------------------------ #
# Password hashing
# ------------------------------------------------------------------ #

def hash_password(plain_password: str) -> str:
    """
    Hash a plain-text password using Argon2id + pepper.
    Pepper is added BEFORE hashing (from SECRET_PEPPER env variable).
    Salt is automatically generated by argon2-cffi.
    """
    settings = get_settings()
    peppered = plain_password + settings.SECRET_PEPPER
    return _ph.hash(peppered)


def verify_password(plain_password: str, hashed_password: str) -> bool:
    """
    Verify a plain-text password against an Argon2id hash.
    Returns True if match, False otherwise.
    Never raises exceptions — all errors are caught internally.
    """
    settings = get_settings()
    peppered = plain_password + settings.SECRET_PEPPER
    try:
        return _ph.verify(hashed_password, peppered)
    except (VerifyMismatchError, InvalidHashError, Exception):
        return False


# ------------------------------------------------------------------ #
# JWT — Access Token
# ------------------------------------------------------------------ #

def create_access_token(
    sub: str,
    role: str,
    family_id: str | None = None,
    expires_delta: timedelta | None = None,
) -> str:
    """
    Create a signed JWT access token.

    Payload:
        sub       — user UUID (subject)
        role      — user role string
        family_id — user's family UUID (or None if not in a family yet)
        exp       — expiry timestamp
        iat       — issued-at timestamp
        jti       — unique JWT ID (prevents replay if token list is stored)
    """
    settings = get_settings()
    now = datetime.now(UTC)
    expire = now + (
        expires_delta
        or timedelta(minutes=settings.ACCESS_TOKEN_EXPIRE_MINUTES)
    )
    payload = {
        "sub": sub,
        "role": role,
        "family_id": family_id,
        "exp": expire,
        "iat": now,
        "jti": secrets.token_hex(16),
    }
    return jwt.encode(
        payload,
        settings.SECRET_KEY,
        algorithm=settings.JWT_ALGORITHM,
    )


def decode_access_token(token: str) -> dict:
    """
    Decode and validate a JWT access token.
    Raises JWTError if the token is invalid or expired.

    CVE-1 FIX: Algorithm is hardcoded to HS256 to prevent algorithm
    confusion attacks (e.g. attacker switching to 'none' or RS256).
    Required claims are enforced to reject malformed tokens early.
    """
    settings = get_settings()
    return jwt.decode(
        token,
        settings.SECRET_KEY,
        algorithms=["HS256"],  # hardcode — never read from config
        options={
            "verify_aud": False,
            "require": ["exp", "iat", "sub", "jti"],
        },
    )


# ------------------------------------------------------------------ #
# Refresh Token
# ------------------------------------------------------------------ #

def create_refresh_token() -> str:
    """
    Generate a cryptographically secure random refresh token.
    Returns the PLAIN token (to be sent to client).
    Always store the HASHED version in the database.
    """
    return secrets.token_hex(32)  # 256-bit entropy


def hash_token(token: str) -> str:
    """
    SHA-256 hash a refresh token for secure storage.
    If the database is compromised, raw tokens remain unknown.
    """
    return hashlib.sha256(token.encode()).hexdigest()
